services:
  products-api:
    build:
      context: ./backend/services/products
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - minio
    networks:
      - app-net

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ecom}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ecom_pass}
      POSTGRES_DB: ${POSTGRES_DB:-ecomdb}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-net

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    volumes:
      - minio-data:/data
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-net
    stdin_open: true
    tty: true

networks:
  app-net:

volumes:
  pgdata:
  minio-data:

